routes/web.php
        Inspiration::where('company_id', $company->id)
                ->update(['is_published' => 1]);

        App\Models\Venue::where('company_id', $company->id)
                ->update(['is_published' => 1]);

        App\Models\Product::where('company_id', $company->id)
                ->update(['is_published' => 1]);

        if($agent->isDesktop()){
            return redirect()->route('dashboard.profile.index',['tab' => 'business'])->with('success', 'Congratulations your profile is now live.');
        }else{
            return redirect()->route('mobile.profile.live');
        }
    }
    if($request->api == 1){
        return $tokenResult = Auth::user()->createToken('Designa Password Grant Client');
    }

    return redirect('/');
})->name('autologin');


Route::get('getlogs', function(Request $request){
    $companies = Company::all();
    if($request->type == "registrations"){
        $list = User::whereHas('company');

        if($request->date){
            $list->whereDate('created_at', $request->date);
        }

    }else{
        if($request->supplier){
            $list = User::whereType('supplier')->whereHas('company', function($q) use($request){
                $q->whereId($request->supplier);
            });
        }else{
            $list = User::whereType('supplier')->whereHas('company');
        }

        if($request->date){
            $list->whereHas('activities', function($q) use($request){
                $q->whereType('LOGIN')->whereDate('created_at',$request->date);
            });
        }
    }


    $suppliers = $list->get();

    if($request->type == "registrations"){
        return view('tool.registrations', compact('suppliers'));
    }else{
        return view('tool.logins', compact('suppliers', 'companies'));
    }

    // $html = '<table border="1" cellpadding="0" cellspacing="0">
    //             <thead>
    //                 <tr>
    //                     <th>Client Number</th>
    //                     <th>Client Name</th>
    //                     <th>Date Registered</th>
    //                     <th>Last Loging Date</th>
    //                     <th>No. of Logins</th>
    //                 </tr>
    //             </thead>
    //             <tbody>
    //         ';
    // foreach($suppliers as $supplier){
    //     $html .= "  <tr>
    //                     <td>$supplier->id</td>
    //                     <td>" . optional($supplier->company)->name . "</td>
    //                     <td>" . $supplier->created_at->format('d/m/Y') . "</td>
    //                     <td>" . optional($supplier->activities()->orderBy('created_at', 'DESC')->first())->created_at . "</td>
    //                     <td>". $supplier->activities()->whereType('LOGIN')->count()  ."</td>
    //                 </tr>
    //             ";
    // }

    // $html .= "</tbody>
    //             </table>
    //         ";

    // return $html;
});


Route::post('/login/web', 'Auth\LoginController@loginWebApi')->name('login.web');

Auth::routes(['verify' => true]);

Route::get('/product-preview', function(){
    return view('site.product-preview');
});

Route::get('inquiry-mail', function(){
    return new App\Mail\Site\InquiryMail("hehe");
});




Route::get('generage32', 'Dashboard\InspirationController@generate32');

// for dashboard routes
    include "web/dashboard.php";

    Route::get('/statistics', 'Dashboard\ActivityController@statistics')->name('activity.statistics');
    Route::post('/statistics', 'Dashboard\ActivityController@statistics')->name('activity.statistics');
    Route::get('/stats', 'Dashboard\ActivityController@getData')->name('activity.stats');
    Route::post('/stats', 'Dashboard\ActivityController@getData')->name('activity.stats');
// for user routes
    include "web/user.php";



Route::get('searchlocation', function(Request $request){
    $lat = $request->lat;
    $lng = $request->lng;
    return $companyIds = Location::select('locationable_id',
        DB::raw("6367 * acos(cos(radians(" . $lat . "))
            * cos(radians(locations.latitude))
            * cos(radians(locations.longitude) - radians(" . $lng . "))
            + sin(radians(" .$lat. "))
            * sin(radians(locations.latitude))) AS distance"))
        ->having('distance', '<', 25)
        ->orderBy('distance', 'asc')
        ->groupBy('locationable_id')
        ->get();

    $results = Company::find($companyIds);

    return $results;
});

Route::post('isloggedin', function(Request $request){
    if($request->user()){
        return 1;
    }

    return 0;
});


Route::get('randomfeature', function(){
    $inspirations = App\Models\Inspiration::all();
    foreach($inspirations as $inspiration){
        $inspiration->featured = random_int(0, 1);
        $inspiration->save();
    }
});

Route::get('migrations', function(){
    $files =   collect(\File::files(database_path('migrations')))
        ->sortBy(function ($q) {
            return str_replace('.php', '', pathinfo($q)['filename']);
        })
        ->map(function($q){
            $migration_file = str_replace('.php', '', pathinfo($q)['filename']);
            \DB::insert('insert INTO migrations (migration, batch) VALUES (?, ?)', [$migration_file, 1]);
            // return pathinfo($q)['filename'];
        });

    return $files;
});


// landing pages
    Route::get('/landing', 'Site\HomeController@mobileLanding')->name('mobile')->middleware('check.for.us.redirect');
    Route::get('/covid-free-events', 'Site\HomeController@landing1')->name('landingpage-2')->middleware('check.for.us.redirect');
    Route::get('/3d-technology', 'Site\HomeController@landing2')->name('landingpage-3d-techonology')->middleware('check.for.us.redirect');
    Route::get('/cost-effective', 'Site\HomeController@landing3')->name('landingpage-3')->middleware('check.for.us.redirect');
    Route::get('/venue-directory', 'Site\HomeController@venueDirectory')->name('landing.venue.directory')->middleware('check.for.us.redirect');
    Route::get('/venue-tours', 'Site\HomeController@venueTours')->name('landing.venue.tours')->middleware('check.for.us.redirect');
    Route::get('/contest-registration', 'Site\HomeController@contestRegistration')->name('landing.contest-registration')->middleware('check.for.us.redirect');
    Route::post('/contest-3d-registration', 'Site\HomeController@contestRegistrationSend')->name('landing.contest-post');

    Route::post('/venue-marketing-usa-send-email','Site\HomeController@venueMarketingUsaSendEmail')->name('landing.venue-marketing-usa-send-email');
    Route::get('/venue-marketing-usa-preregister','Site\HomeController@venueMarketingUsaPreregister')->name('landing.venue-marketing-usa-preregister');
    Route::get('/venue-marketing-usa','Site\HomeController@venueMarketingUsa')->name('landing.venue-marketing-usa');


Route::get('/email-verified', 'Site\HomeController@mobileEmailVerified')->name('email.verified');
Route::get('/profile-live', 'Site\HomeController@mobileProfileLiveLanding')->name('mobile.profile.live');

Route::group(['as' => 'site.', 'middleware' => ['checkmobile', 'check.for.us.redirect']], function(){
    Route::get('/', 'Site\HomeController@index')->name('site.index');

    // 3d Request
    Route::get('request-3d', 'Site\Request3dController@index')->name('request-3d-form');
    Route::post('request-3d', 'Site\Request3dController@submit')->name('request-3d-form.submit');

    // Pricing
    Route::get('pricing', 'Site\PricingController@index')->name('pricing.index');

    // Subscription
    Route::get('subscription', 'Site\SubscriptionController@index')->name('subscription');
    Route::post('subscription', 'Site\SubscriptionController@store')->name('subscription.store');

    // Inquiry
    Route::post('request-demo-covid', 'Site\HomeController@requestDemoCovid')->name('requestdemo.covid');
    Route::post('inquiry', 'Site\HomeController@sendInquiry')->name('sendinquiry');
    Route::post('register-webinar', 'Site\HomeController@registerWebinar')->name('registerWebinar');
    Route::post('request-white-glove-service', 'Site\HomeController@requestWhiteGloveService')->name('registerEmail');
    Route::post('register-email', 'Site\HomeController@registerEmail')->name('registerEmail');
    Route::post('register-newsletter-email', 'Site\HomeController@registerNewsLetterEmail')->name('registerEmail');
    Route::post('request-demo', 'Site\HomeController@requestDemo')->name('requestdemo');
    Route::get('event-registration', 'Site\HomeController@eventRegistration')->name('eventRegister');
    Route::post('event-registration', 'Site\HomeController@eventRegistrationPost')->name('eventRegisterPost');

    Route::get('for-supplier/{tab}', function($tab ){
        $blogs = App\Models\Blog::where('is_published', 1)->orderBY('id', 'DESC')->get();
        $recent_blogs = App\Models\Blog::where('is_published', 1)->orderBY('id', 'DESC')->limit(3)->get();
        // echo $tab;
        $tab_blog = request()->get('tab');

        $blog = explode('/',$tab_blog);
        // echo $blog[0].'<br/>';
        try {
            $tag_blog = $blog[0];
            $get_blog = $blogs[0];
        } catch (\Throwable $th) {
            $get_blog = '';
            $tag_blog = '';
        }
        return view('site.for-supplier-support-pages.' . $tab, compact('blogs','recent_blogs','get_blog','tag_blog'));

    })->name('for-supplier');

    Route::get('/for-supplier/resources/blogs','Site\BlogController@index')->name('blog.index');
    Route::get('/for-supplier/resources/blogs/{id}','Site\BlogController@show')->name('blog.show');
    Route::get('business-profile-assistance-form', 'Site\HomeController@assistanceForm')->name('supplier.assistance.form');
    Route::post('business-profile-assistance-form', 'Site\HomeController@assistanceFormStore')->name('supplier.assistance.form.post');

    // Search
    Route::post('search', 'Site\SearchController@search')->name('search');

resources/views/site/includes/menus/footer-sitemap.blade.php
<div class="site-map d-none d-sm-block">
    <div class="container">
        <div class="sections">
            <div class="section">
                <h5>Browse Photos</h5>
                @foreach($data['caters'] as $cater)
                    <a href="#">{{ $cater->name }}</a>
                @endforeach
            </div>
            <div class="section">
                <h5>Find Venues</h5>
                @foreach($data['venue_types'] as $venue)
                    <a href="{{ route('site.venue.index', ['cat' => $venue->slug]) }}">{{ $venue->name }}</a>
                @endforeach
            </div>
            <div class="section">
                <h5>Find Suppliers</h5>
                @foreach($data['suppliers'] as $supplier)
                    <a href="{{ route('site.supplier.index', ['cat' => $supplier->name]) }}">{{ $supplier->display_name }}</a>
                @endforeach
            </div>
            <div class="section">
                <h5>Find Decor</h5>
                @foreach($data['products'] as $product)
                    <a href="{{ route('site.decor.index', ['cat' => $product->slug]) }}">{{ $product->name }}</a>
                @endforeach

            </div>
            <div class="section">
                <h5>Get Help</h5>
                <a href="/for-supplier">For Supplier</a>
            </div>
        </div>

        <div class="text-center">
            
        </div>
    </div>
</div>

resources/views/site/includes/menus/navbar.blade.php
<div class="top-menu">
    <nav class="navbar navbar-expand-lg p-0">
        <div class="container">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item @if(Request::segment(1) == "inspiration") active @endif ">
                        <a class="nav-link" href="{{ route('site.inspiration.index') }}"><i class="fa fa-camera"></i> Inspiration <span class="sr-only">(current)</span></a>
                        <div class="mega-menu">
                            <div class="sections">
                                @foreach($data['caters'] as $cater)
                                    <div class="section">
                                        <h4 class="title mb-0">
                                            <a class="text-orange" style="text-weight:bold; font-size:16px" @if(Request::get('cat') == $cater->slug) style="color:orange" @endif  href="{{ route('site.inspiration.index', ['cat' => $cater->slug]) }}">{{ $cater->name }}</a>
                                        </h4>
                                        @foreach($cater->styles as $style)
                                            <a @if(Request::get('cat') == $style->slug) style="color:orange" @endif href="{{ route('site.inspiration.index',['cat' => $style->slug]) }}">{{ $style->name }}</a>
                                        @endforeach
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </li>
                    <li class="nav-item @if(Request::segment(1) == "venue") active @endif">
                        <a class="nav-link" href="{{ route('site.venue.index') }}"><i class="fa fa-map-marker"></i> Find Venue</a>
                        <div class="mega-menu">
                            <div class="sections">
                                @php 
                                    $venues_counter = 1;
                                    $venue_limit = 4; 
                                @endphp
                                @foreach($data['venue_types'] as $venue)
                                    @if($venues_counter == 1)
                                        <div class="section">
                                    @endif
                                        <a @if(Request::get('cat') == $style->slug) style="color:orange" @endif  href="{{ route('site.venue.index', ['cat' => $venue->slug]) }}">{{ $venue->name }}</a>
                                    
                                    @if($venues_counter == $venue_limit)
                                        </div>
                                            @php $venues_counter = 1; @endphp
                                    @else
                                        @php $venues_counter++ @endphp
                                    @endif
                                @endforeach
                            </div>
                        </div>
                    </li>
                    <li class="nav-item @if(Request::segment(1) == "supplier") active @endif">
                        <a class="nav-link" href="{{ route('site.supplier.index') }}"><i class="fa fa-truck"></i> Find Supplier</a>
                        <div class="mega-menu">
                             <div class="sections">
                                @php 
                                    $suppliers_counter = 1;
                                    $supplier_limit = 6; 
                                @endphp
                                @foreach($data['suppliers'] as $supplier)
                                    @if($suppliers_counter == 1)
                                        <div class="section">
                                    @endif
                                        <a @if(Request::get('cat') == $style->slug) style="color:orange" @endif  href="{{ route('site.supplier.index', ['cat' => $supplier->name]) }}">{{ $supplier->display_name }}</a>
                                    
                                    @if($suppliers_counter == $supplier_limit)
                                        </div>
                                            @php $suppliers_counter = 1; @endphp
                                    @else
                                        @php $suppliers_counter++ @endphp
                                    @endif
                                @endforeach
                            </div>
                        </div>
                    </li>
                    <li class="nav-item @if(Request::segment(1) == "decor") active @endif">
                        <a class="nav-link" href="{{ route('site.decor.index') }}"><i class="fa fa-search"></i> Find Décor</a>
                        <div class="mega-menu">
                             <div class="sections">
                                @php 
                                    $products_counter = 1;
                                    $product_limit = 6; 
                                @endphp
                                @foreach($data['products'] as $product)
                                    @if($products_counter == 1)
                                        <div class="section">
                                    @endif
                                    <div>
                                        @if(count($product->styles))
                                            <div>
                                                <a style="display: inline" @if(Request::get('cat') == $style->slug) style="color:orange" @endif  href="{{ route('site.decor.index',['cat' => $product->slug]) }}">{{ $product->name }}</a>
                                                <a style="display: inline" class="ml-1" data-toggle="collapse" href="#collapse-{{ $product->id }}" role="button" aria-expanded="false" aria-controls="collapse-{{ $product->id }}">
                                                    <i class="fa" aria-hidden="true"></i>
                                                </a>
                                            </div>
                                        @else
                                            <a @if(Request::get('cat') == $style->slug) style="color:orange" @endif  href="{{ route('site.decor.index',['cat' => $product->slug]) }}">{{ $product->name }}</a>
                                        @endif
                                            <div class="pl-3 collapse multi-collapse" id="collapse-{{ $product->id }}">
                                                @foreach($product->styles as $style)
                                                    <a @if(Request::get('cat') == $style->slug) style="color:orange" @endif  href="{{ route('site.decor.index',['cat' => $style->slug]) }}">{{ $style->name }}</a>
                                                @endforeach
                                            </div>
                                    </div>
                                    @if($products_counter >= $product_limit)
                                        </div>
                                            @php $products_counter = 1; @endphp
                                    @else
                                        @php $products_counter++ @endphp
                                    @endif
                                @endforeach
                            </div>
                        </div>
                    </li>
                    {{-- <li class="nav-item">
                        <a class="nav-link" href="{{ route('site.pricing.index') }}"><i class="fa fa-dollar"></i> Pricing</a>
                    </li> --}}
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fa fa-comment"></i> Get Help</a>
                        <div class="mega-menu">
                             <div class="sections">
                                 <div class="section">
                                    <a href="/for-supplier/supplier-hub">For Supplier</a>
                                 </div>
                             </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>

resources/views/site/includes/menus/user-side-menu.blade.php
<div class="site-side-link">
    <div class="profile mb-3 text-center">
        <img src="{{ Auth::user()->getProfilePicture() }}" class="mw-100 rounded-circle mx-auto d-block mb-2" style="width:80px; height: 80px;" alt="User Image">
        <h3 class="text-orange">{{ Auth::user()->name }}</h3>
        <hr>
    </div>

    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link @if(Request::segment(2) == "profile") active @endif"  href="{{ route('user.profile.index') }}"><i class="fa fa-user"></i> Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link @if(Request::segment(2) == "saved") active @endif" href="{{ route('user.saved.inspirations') }}"><i class="fa fa-tag"></i> Saved Items</a>
        </li>
        <li class="nav-item">
            <a class="nav-link @if(Request::segment(2) == "qoute") active @endif" href="{{ route('user.qoute.index') }}"><i class="fa fa-file"></i> Quotes</a>
        </li>
        <li class="nav-item">
            <a class="nav-link @if(Request::segment(2) == "project") active @endif" href="{{ route('user.event-board.index') }}"><i class="fa fa-image"></i> Event Board</a>
        </li>
        <li class="nav-item">
            <a class="nav-link @if(Request::segment(2) == "notification") active @endif " href="{{ route('user.notification.index') }}"><i class="fa fa-bell"></i> Notification</a>
        </li>
        <li class="nav-item">
            <a class="nav-link @if(Request::segment(2) == "profile") active @endif" href="{{ route('logout') }}"
                   onclick="event.preventDefault();
                                 document.getElementById('logout-form').submit();"><i class="fa fa-sign-out"></i> Logout</a>
                
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        </li>
    </ul>
</div>